### ISSUE TITLE
Could you help me to get the data sheet of D7s?

### ISSUE THREAD

**Issue by thhuang3** [philwinn/omron-d7s-i2c-driver#1]
Dear Mr. Winnekens:
   I am looking for this module to implement a project, but I just can only obtain brief introduction of it.
Where can I get more detail information about it?

Thanks so much

**Comment by philwinn** [comment]
Is your issue still relevant? Unfortunately, I didn't receive an email notification by Github...
Anyway, further technical description can be obtained [from this document](https://www.futurashop.it/image/catalog/data/Download/7100-BREAKOUT019/D7S.pdf).

**Comment by thhuang3** [comment]
It's OK, we decided to use normal G sensor to replace it due to the price is too expensive, thanks for your reply.
thhuang3
    在 2020年4月17日 星期五 下午06:46:02 [GMT+8]， Philipp Winnekens<notifications@github.com> 寫道：  
 
 


Is your issue still relevant? Unfortunately, I didn't receive an email notification by Github...
