### ISSUE TITLE
DS7.h Complie time error

### ISSUE THREAD

**Issue by kittunotes** [philwinn/omron-d7s-i2c-driver#2]
Getting compile time Error in my Arduino Project.
src/D7S.h:40:1: warning: 'typedef' was ignored in this declaration
   40 | typedef enum d7s_status {
      | ^~~~~~~

**Comment by kittunotes** [comment]
typedef enum d7s_status {
      | ^~~~~~~
c:\Arduino\libraries\D7S_Arduino_Library-1.0.0\src/D7S.h:49:1: warning: 'typedef' was ignored in this declaration
   49 | typedef enum d7s_axis_settings {
      | ^~~~~~~
c:\\Arduino\libraries\D7S_Arduino_Library-1.0.0\src/D7S.h:58:1: warning: 'typedef' was ignored in this declaration
   58 | typedef enum d7s_axis_state {
      | ^~~~~~~
c:\\Arduino\libraries\D7S_Arduino_Library-1.0.0\src/D7S.h:65:1: warning: 'typedef' was ignored in this declaration
   65 | typedef enum d7s_threshold {
      | ^~~~~~~
c:\\Arduino\libraries\D7S_Arduino_Library-1.0.0\src/D7S.h:72:9: error: 'OK' conflicts with a previous declaration
   72 |    OK = 0,
      |         ^
In file included from C:\\Arduino15\packages\esp8266\hardware\esp8266\3.1.1\cores\esp8266/esp8266_peri.h:27,
                 from C:\\Arduino15\packages\esp8266\hardware\esp8266\3.1.1\cores\esp8266/Arduino.h:39,
                 from C:\Users\abhishek1.v\AppData\Local\Temp\arduino-sketch-A24F9F7488124803E6565F8EA00DC214\sketch\AdvancedSeismograph.ino.cpp:1:
C:\\Arduino15\packages\esp8266\hardware\esp8266\3.1.1/tools/sdk/include/c_types.h:71:5: note: previous declaration 'STATUS OK'
   71 |     OK = 0,
      |     ^~
In file included from C:\Users\abhishek1.v\AppData\Local\Temp\.arduinoIDE-unsaved202311-16508-1it484v.jpzzf\AdvancedSeismograph\AdvancedSeismograph.ino:22:
C:\Arduino\libraries\D7S_Arduino_Library-1.0.0\src/D7S.h:71:1: warning: 'typedef' was ignored in this declaration
   71 | typedef enum d7s_mode_status {
      | ^~~~~~~
C:\Arduino\libraries\D7S_Arduino_Library-1.0.0\src/D7S.h:77:1: warning: 'typedef' was ignored in this declaration
   77 | typedef enum d7s_interrupt_event {
      | ^~~~~~~

**Comment by kittunotes** [comment]
Please help

**Comment by philwinn** [comment]
Your project is broken, not this library.
